const $=s=>document.querySelector(s);let connected=false;let token='',base=localStorage.getItem('moneycut-server')||'',snapshot=null,template=null;
const labels={queued:'대기',running:'제작 중',done:'완료',needs_attention:'확인 필요',pending:'대기',retry:'재시도 대기',failed:'실패',degraded:'검토 필요',rejected:'이용 근거 부족',checking:'이용 허락 확인',downloading:'다운로드',searched:'검색 완료',partial:'일부 완료',error:'확인 필요'};
function notice(message){$('#notice').textContent=message;$('#notice').hidden=!message}
const CONNECTION_REQUIRED='제작 서버가 아직 연결되지 않았습니다. 현재는 대시보드 화면만 배포된 상태이며, 실제 검색·영상 제작은 서버 연결 후 사용할 수 있습니다.';
function setConnected(value){connected=value;document.querySelectorAll('#create-form button[type="submit"],#link-form button.primary').forEach(b=>{b.disabled=!value;b.title=value?'':CONNECTION_REQUIRED});const b=$('#create-form button[type="submit"]');b.textContent=value?'검색하고 제작하기 ↗':'제작 서버 연결 대기';}
async function api(path,body){
 if((!base&&location.hostname.endsWith('github.io'))||(base&&new URL(base).hostname.endsWith('github.io')))throw Error(CONNECTION_REQUIRED);
 if(path==='create'&&!connected)throw Error(CONNECTION_REQUIRED);
 let r;try{r=await fetch(base+'/api/'+path,{method:body===undefined?'GET':'POST',signal:AbortSignal.timeout(20000),headers:{...(token?{Authorization:'Bearer '+token}:{}),...(body===undefined?{}:{'Content-Type':'application/json'})},body:body===undefined?undefined:JSON.stringify(body)})}catch{throw Error('제작 서버에 접속하지 못했습니다. 서버 실행 상태와 연결 주소를 확인하세요.')}
 if(!(r.headers.get('content-type')||'').toLowerCase().includes('application/json'))throw Error('제작 서버 대신 웹 페이지가 응답했습니다. 연결 및 설정에서 실제 제작 서버 주소를 확인하세요.');
 let data;try{data=await r.json()}catch{throw Error('제작 서버 응답을 읽지 못했습니다. 잠시 후 다시 연결하세요.')}
 if(!r.ok)throw Error(typeof data?.error==='string'?data.error:'서버 요청을 완료하지 못했습니다.');return data
}

function view(id){document.querySelectorAll('.view').forEach(v=>v.hidden=v.id!==id);document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));$('#heading').textContent=document.querySelector(`[data-view="${id}"]`).textContent}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>view(b.dataset.view));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>view(b.dataset.go));
const text=(tag,value,className)=>{const n=document.createElement(tag);n.textContent=value;if(className)n.className=className;return n};
async function action(fn){try{notice('');await fn()}catch(e){notice(e.message)}}
function jobList(target,jobs){target.replaceChildren();if(!jobs.length){target.textContent='아직 등록된 작업이 없습니다.';return}for(const j of jobs){const row=text('div','','job'),info=text('div','');info.append(text('strong',j.title||j.id),text('p',`${labels[j.status]||j.status} · ${j.done}/${j.total} 단계`));const progress=document.createElement('progress');progress.max=Math.max(1,j.total);progress.value=j.done;info.append(progress);if(j.error)info.append(text('p',j.error));row.append(info);if(j.status==='needs_attention'){const b=text('button','실패 단계 재시도');b.onclick=()=>action(async()=>{await api('retry',{id:j.id});await refresh()});row.append(b)}target.append(row)}}
async function refresh(){try{snapshot=await api('state');if(!snapshot||!Array.isArray(snapshot.jobs)||!Array.isArray(snapshot.sources)||!Array.isArray(snapshot.results)||!snapshot.config?.template||!snapshot.services)throw Error('제작 서버 상태 응답 형식이 올바르지 않습니다.');setConnected(!snapshot.preview_only&&!!snapshot.services.OpenAI);if(snapshot.drive_url)$('#drive-link').href=snapshot.drive_url;$('#connection').textContent=snapshot.preview_only?'미리보기 모드':'제작 서버 연결됨';if(snapshot.preview_only)notice('로컬 미리보기입니다. 실제 검색·제작 작업자는 아직 시작하지 않았습니다.');$('#count-all').textContent=snapshot.jobs.length;$('#count-running').textContent=snapshot.jobs.filter(j=>['running','queued'].includes(j.status)).length;$('#count-done').textContent=snapshot.jobs.filter(j=>j.status==='done').length;$('#count-review').textContent=snapshot.jobs.filter(j=>j.status==='needs_attention').length;jobList($('#recent-jobs'),snapshot.jobs.slice(-4).reverse());jobList($('#job-list'),[...snapshot.jobs].reverse());const sl=$('#source-list');sl.replaceChildren();if(!snapshot.sources.length)sl.textContent='검색 기록이 없습니다.';snapshot.sources.forEach(s=>{const r=text('div','','job');r.append(text('strong',s.title||s.id),text('span',labels[s.state]||s.state,'status'));if(s.error)r.append(text('p',s.error));sl.append(r)});if(!template){template=snapshot.config.template;fillTemplate()}const status=$('#service-status');status.replaceChildren();for(const [name,ready]of Object.entries(snapshot.services)){const r=text('div','','service');r.append(text('strong',name),text('span',ready?'설정 등록됨':'추가 설정 필요'));status.append(r)}renderResults(snapshot.results);return true}catch(e){setConnected(false);snapshot=null;$('#connection').textContent='서버 연결 필요';notice(e.message);return false}}
function renderResults(results){const el=$('#result-list');el.replaceChildren();if(!results.length){el.textContent='완료된 결과가 없습니다.';return}for(const r of results){const card=text('div','','result-card');card.append(text('strong',r.title),text('p',r.review?'검토 필요 · 자동 전송 보류':'검증 완료'));if(r.drive_url){const a=text('a','Drive에서 보기 ↗');a.href=r.drive_url;a.target='_blank';a.rel='noopener';card.append(a)}for(const f of r.files){const b=text('button',f);b.onclick=()=>action(async()=>{const res=await fetch(base+'/api/file?path='+encodeURIComponent(r.path+'/'+f),{headers:token?{Authorization:'Bearer '+token}:{}});if(!res.ok)throw Error('파일을 불러오지 못했습니다.');const url=URL.createObjectURL(await res.blob()),a=document.createElement('a');a.href=url;a.download=f;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000)});card.append(b)}el.append(card)}}
$('#strength').oninput=()=>$('#strength-value').value=$('#strength').value;
function config(){return {source_target:+$('#source-count').value,clips:+$('#clip-count').value,min_length:$('#length').value==='60'?30:20,max_length:+$('#length').value,hook_strength:+$('#strength').value}}
$('#create-form').onsubmit=e=>{e.preventDefault();action(async()=>{await api('create',{query:$('#query').value,config:config()});notice('검색 작업을 등록했습니다. 이용 허락 확인 후 제작을 진행합니다.');await refresh();view('queue')})};
$('#link-form').onsubmit=e=>{e.preventDefault();action(async()=>{await api('create',{query:'지정 영상',links:$('#links').value.split(/\s+/).filter(Boolean),config:config()});await refresh();view('queue')})};
$('#connection-form').onsubmit=e=>{e.preventDefault();action(async()=>{setConnected(false);const raw=$('#server-url').value.trim();if(raw){const u=new URL(raw);if(u.protocol!=='https:'&&!['localhost','127.0.0.1'].includes(u.hostname))throw Error('외부 서버는 HTTPS 주소를 사용하세요.');base=u.origin}else base='';token=$('#server-token').value;localStorage.setItem('moneycut-server',base);if(await refresh())notice('제작 서버에 연결했습니다.')})};$('#server-url').value=base;$('#refresh').onclick=()=>refresh();
for(const [key,label,fields] of [['main','메인 타이틀',['x','y','w','h','size']],['sub','서브 타이틀',['x','y','w','h','size']],['video','원본 영상',['x','y','w']],['subtitle','자막',['x','y','w','h','size']]]){const group=text('div','','geometry');group.append(text('h3',label));const row=text('div','','form-row');for(const f of fields){const label=text('label',({x:'가로 위치',y:'세로 위치',w:'너비',h:'높이',size:'글자 크기'})[f]),input=document.createElement('input');input.type='number';input.name=key+'_'+f;input.min=f==='x'||f==='y'?'0':'1';input.max='1920';input.required=true;label.append(input);row.append(label)}group.append(row);$('#geometry-fields').append(group)}
function fillTemplate(){for(const [k,v]of Object.entries(template||{})){const el=$('#design-form').elements.namedItem(k);if(el){if(el.type==='checkbox')el.checked=v;else el.value=v}}}
function readTemplate(){if(!template)throw Error('먼저 제작 서버에 연결해 프리셋을 불러오세요.');const t={...template};for(const el of $('#design-form').elements){if(!el.name)continue;t[el.name]=el.type==='number'?+el.value:el.type==='checkbox'?el.checked:el.value}return t}
$('#design-form').onsubmit=e=>{e.preventDefault();action(async()=>{template=(await api('template',{template:readTemplate()})).template;notice('대판 프리셋을 저장했습니다.')})};
$('#preset-export').onclick=()=>action(()=>{const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(readTemplate(),null,2)],{type:'application/json'}));a.href=url;a.download='MONEY-CUT-template.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)});
$('#preset-import').onchange=e=>action(async()=>{const file=e.target.files[0];if(!file)return;if(file.size>100000)throw Error('프리셋 파일이 너무 큽니다.');const imported=JSON.parse(await file.text());template=(await api('template',{template:imported})).template;fillTemplate();notice('프리셋을 불러왔습니다.')});
setConnected(false);refresh();setInterval(()=>{if(!document.hidden)refresh()},15000);

$("#design-preview").onclick=()=>action(async()=>{const r=await fetch(base+"/api/preview",{method:"POST",headers:{"Content-Type":"application/json",...(token?{Authorization:"Bearer "+token}:{})},body:JSON.stringify({template:readTemplate()})});if(!r.ok)throw Error("미리보기를 만들지 못했습니다.");const img=$("#design-render");if(img.src.startsWith("blob:"))URL.revokeObjectURL(img.src);img.src=URL.createObjectURL(await r.blob());img.hidden=false;});

$('#drive-link').addEventListener('click',e=>{if($('#drive-link').getAttribute('href')==='#'){e.preventDefault();notice('제작 서버 연결 후 Drive 폴더를 열 수 있습니다.');}});
